export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTHENTICATED = 'AUTHENTICATED';
export const SEARCH_ARTISTS = 'SEARCH_ARTISTS';
export const SEARCHING_ARTISTS = 'SEARCHING_ARTISTS';
export const SEARCH_ARTISTS_ERROR = 'SEARCH_ARTISTS_ERROR';